# Generated by Django 5.1 on 2024-08-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResource', '0002_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='localtion',
            new_name='location',
        ),
    ]
